# Generated by Django 5.1.1 on 2024-10-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="date_of_first_mail",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата первой отправки"
            ),
        ),
    ]
