# Generated by Django 5.1.1 on 2024-10-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_alter_mailing_date_of_first_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="client_id",
            field=models.ManyToManyField(
                to="newsletter.client", verbose_name="Клиенты"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="message_id",
            field=models.OneToOneField(
                default=1,
                help_text="Выберите сообщение",
                on_delete=django.db.models.deletion.CASCADE,
                to="newsletter.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
